### ISSUE TITLE
Feature request: SMAA T2x

### ISSUE THREAD

**Issue by Eniff** [martymcmodding/iMMERSE#2]
Hello,

I really appreciate your work for these filters.
Now that there are filters to analyze vectors in the scene like your Launchpad filter, wouldn't Temporal SMAA also be possible to implement?
I really like SMAA T2x in games that support it, altough there are not many. I think of it as the best look/cost anti-aliasing technique. I know it wouldn't be as good quality or as fast as if it was built into the game engine but would it be theoritically possible with reshade?

**Comment by martymcmodding** [comment]
Hi,

honestly, I've tried, but it's not doable with a quality that is remotely satisfying. The issue is, we don't have a jittered camera, meaning that we don't get any supersampling per se and can only hope the same feature has been sampled differently the previous frame. However this means that the pixel data doesn't match with current frame - which is bad for optical flow which I use to reproject current frames.

So whenever the previous frame would yield differently sampled data that would actually improve things in the current frame when blended - optical flow fails.

There is TFAA for ReShade which attempts this and I've implemented my own ad-hoc TAA experiments but when you zoom in a bit, it looks really bad. Like vaseline smeared onto a glass plate and shaken - the scene wobbles weirdly and becomes more grainy rather than better. So it's not going to happen anytime soon.

However, given in-engine motion vectors, this can be attempted. With them, at least the reprojection doesn't suck and it's basically an unpredictable TAA at that point. With the ReShade addon API, this can be done on per-game basis. I'm semi-working on a project surrounding that, but I won't have anything to show for anytime soon.

**Comment by Eniff** [comment]
Thank you for the explanation and insight!

It is also promising that it could be done if we extract the in-engine vectors on a per-game basis. I hope I get to a level once where I can do this for some of my games.

Thank you again for your work for the community, I have been using your QUINT filter pack for long time, the depth sharpening filter, when it works, is not comparable to anything else and it helps a lot with blurry TAA in a lots of games.

Sorry for asking question again but there is a game (World of Tanks) which jitters the depth buffer as well when I turn on the in-game TAA and it makes the end result also jitter a bit when I turn on QUINT_Sharpen in that game. Is there a way the circumvent that or am I out of luck for that game? Regular CAS still works so it is not a huge problem. ( I have not seen another game that did that to the depth buffer)

**Comment by martymcmodding** [comment]
Hmm, if you switch to simple mode, it doesn't read the depth buffer and sharpens based on color only, that should always work. If these results are superior to CAS, that's up to you to decide :P It uses 4 instead of 9 samples so it should be faster than CAS.

**Comment by Eniff** [comment]
Thank you for your recommendation! I will definitely try it and compare them.

**Comment by Maruzeru** [comment]
I tried the Immerse MXAO on a few games, even on ones with jittering depth buffer, and it seems the end result is not not jittering like it was in quint for me. So it seems to be fixed.
