### ISSUE TITLE
Immerse MXAO is causing eyebrow graphical glitch

### ISSUE THREAD

**Issue by IamTheAllRangeAtomic** [martymcmodding/iMMERSE#6]
screen shot - https://i.imgur.com/kCLDiKq.png

I'm not sure if I can ask how to resolve this here, but whenever I disable the MXAO setting, it fixes the glitch you see on the eyebrows, but I no longer have that effect enabled which I like.

Is there a way to have this not effect the eyebrows?

**Comment by martymcmodding** [comment]
That's not a glitch but intended behavior. The eyebrows are their own 3D model that slightly hovers above the face, presumably to prevent clipping. 

SSAO tends to expose issues with assets that otherwise go unnoticed. The reason ENB's AO doesn't cause this as well is because it doesn't resolve such tiny details which comes with it's own tradeoffs.  

In any case, there's nothing I can do to selectively apply effects on such areas and if the 3D model was authored properly, it wouldn't be necessary either.
